spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    consumer:
      group-id: "thesis-consumer"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        specific:
          avro:
            reader: "true"
kafka:
  topic:
    producer-one:
      user-actions: "mk.ukim.finki.thesis.producer-one.user-actions"
logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
#    org.springframework: DEBUG
server:
  port: 8888