spring:
  application:
    name: consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/consumer-actions
    username: postgres
    password: admin
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    consumer:
      group-id: "thesis-consumer"
      keyDeserializer: "mk.ukim.finki.thesis.common.serializer.MessageKeyDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        specific:
          avro:
            reader: "true"
kafka:
  topic:
    producer-one:
      user-actions: "mk.ukim.finki.thesis.producer-one.user-actions"

#logging:
#  level:
#    org.apache.kafka: INFO
#    org.springframework.kafka: INFO
#    org.springframework: INFO
#    org.hibernate: DEBUG

server:
  port: 8888